name: Deploy

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > keyfile
        chmod 600 keyfile
        mkdir -p ~/.ssh
        cp known_hosts ~/.ssh/known_hosts
        ssh -t -i keyfile ubuntu@ec2-54-179-188-93.ap-southeast-1.compute.amazonaws.com 
    - name: Run deployment script
      run: |
        ssh -i keyfile -o StrictHostKeyChecking=no ubuntu@ec2-54-179-188-93.ap-southeast-1.compute.amazonaws.com << 'EOF'
          cd staff-management-4
          git pull origin main
          npm install
          sudo pm2 delete all || true
          sudo pm2 start ecosystem.config.js --env production
        EOF

    - name: Clean up
      run: |
        rm -f keyfile
        rm -f ~/.ssh/known_hosts

       